### ISSUE TITLE
No applications shown

### ISSUE THREAD

**Issue by rainerleber** [rkrmr33/argo2go-support#2]
Hi thank you for the application,

I’m unable to see any applications the error is the following:

![IMG_7747](https://github.com/rkrmr33/argo2go-support/assets/39616583/67d2cfcf-de0d-44ed-8d0d-1cb55ba4c2ca)

**Comment by Panzer1119** [comment]
I have the same Problem.

I'm running Argo CD `v2.7.1+5e54351.dirty` and Kubernetes/K3s `v1.26.4+k3s1`

**Comment by Marck** [comment]
Same issue here, it doesn't work at all. Have the newest ArgoCD version (2.7.7) and running on K3s. 
Can you take a look at what is wrong @rkrmr33?

**Comment by rkrmr33** [comment]
Hey all, sorry for the very late response, did not have time to work on this recently.
The good news is that it should be fixed in version `v0.0.3`, which was released today.

Please let me know if it's fixed. I will keep this open for a few days.
Thanks for trying out the app! 😄

**Comment by rainerleber** [comment]
Hey @rkrmr33,

Thank you for trying fixing.
unfortunately it's the same issue.

**Comment by rkrmr33** [comment]
Interesting @rainerleber, could you please share what types of applications you have on this argo-cd (helm/kustomize/directory)?

Nevertheless, I'll try to take another look later today.
Thanks for the quick feedback.

**Comment by Marck** [comment]
I now get a different error (but of the same kind). Hope this helps
![image](https://github.com/rkrmr33/argo2go-support/assets/18088281/8b018efe-2dc8-41a4-a429-5d3c4042c918)

**Comment by rainerleber** [comment]
Now my issue is the same as the one from @Marck

**Comment by rkrmr33** [comment]
Update: I have just released an update which would allow me to get reports of such errors and handle them more quickly. I hope I could resolve this issue as soon as users get the new version and I start getting the reports.

**Comment by rainerleber** [comment]
New error message ![image](https://github.com/rkrmr33/argo2go-support/assets/39616583/a6b260e4-c566-4bd6-8e2a-0b7ba17e2577)

**Comment by rkrmr33** [comment]
Thanks @rainerleber, I believe that helped me resolve the issue now. It was something related to how I was handling `Unauthorized` responses that I got back from ArgoCD.

I think you signed in with username+password and your session just ended. Now if you download the latest update you should be redirected to the login screen.

Let me know if that works now :)

**Comment by rainerleber** [comment]
Unfortunately the old error with the latest version:

![image](https://github.com/rkrmr33/argo2go-support/assets/39616583/e99fa036-887c-421f-b1dd-364308c8bb26)

**Comment by rkrmr33** [comment]
Ok, this issue should be solved as well in the latest version. I think it's caused by applications with multiple sources. I have added partial support for this feature for now, as it appears to be a relatively new feature.

Please let me know if the issue is now resolved or if you see any other issue.

**Comment by rainerleber** [comment]
Hi @rkrmr33 thank you now it works. It's pretty cool
